apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pfa-api.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pfa-api.name" . }}
    helm.sh/chart: {{ include "pfa-api.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pfa-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pfa-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/bin/sh"
            - "-ecx"
            - |
              {{ .Values.image.command }}
          envFrom:
            - configMapRef:
                name: "{{ template "pfa-api.fullname" . }}-env"
          ports:
            - name: http
              containerPort: 4000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: pfa-api-src
              mountPath: "/apps/pfa-api/src"
            - name: pfa-api-babel
              mountPath: "/apps/pfa-api/.babelrc"
            - name: pfa-api-package
              mountPath: "/apps/pfa-api/package.json"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: pfa-api-src
          hostPath:
            path: "{{ .Values.image.package_path }}/src"
            type: Directory
        - name: pfa-api-babel
          hostPath:
            path: "{{ .Values.image.package_path }}/.babelrc"
            type: File
        - name: pfa-api-package
          hostPath:
            path: "{{ .Values.image.package_path }}/package.json"
            type: File

    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
