version: '3'
services:

  pfa-api:
    build:
      context: packages/pfa-api
      dockerfile: Dockerfile
    command: ["yarn", "run", "inspect"]
    environment:
      NODE_ENV: "local"
      SUPPRESS_NO_CONFIG_WARNING: "true"
    volumes:
      - ./packages/pfa-api/src:/apps/pfa-api/src
    depends_on:
      - postgres
    ports:
      - "3030:3030"
      - "5858:5858"

  postgres:
    image: postgres-postgis:11.1-alpine
    environment:
      POSTGRES_USER: pfa_master
      POSTGRES_DB: pro_football_analytics
    volumes:
      - /tmp/nfl_00-18:/tmp/nfl_00-18
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  pg-data: