apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  type: NodePort
  ports:
    - name: postgresql
      port: 5432
      protocol: TCP
      targetPort: postgresql
      nodePort: 30543
  selector:
    app: postgresql
    release: postgres
    role: master