apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: pfa
spec:
  replicas: 1
  serviceName: kafka-cluster
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka
      app.kubernetes.io/instance: pfa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka
        app.kubernetes.io/instance: pfa
    spec:
      imagePullSecrets:
        - name: quay-pull-secret
      containers:
        - name: kafka
          image: quay.io/sean.costello/kafka:2.12-2.2.0
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: "KAFKA_ADVERTISED_HOST_NAME"
              value: "$(MY_POD_NAME).kafka-cluster.$(MY_POD_NAMESPACE).svc"
            - name: "KAFKA_ADVERTISED_LISTENERS"
              value: "PLAINTEXT://:9092"
            - name: "KAFKA_LISTENERS"
              value: "PLAINTEXT://:9092"
            - name: "KAFKA_ADVERTISED_PORT"
              value: "9092"
            - name: "KAFKA_PORT"
              value: "9092"
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "zookeeper.$(MY_POD_NAMESPACE).svc:2181"
            - name: "KAFKA_CREATE_TOPICS"
              value: "events:1:1:compact"
          ports:
            - name: client
              containerPort: 9092
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 5
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: client
            initialDelaySeconds: 15
            timeoutSeconds: 2