apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: pfa
spec:
  replicas: 1
  serviceName: zookeeper-cluster
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper
      app.kubernetes.io/instance: pfa
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper
        app.kubernetes.io/instance: pfa
    spec:
      containers:
        - name: zookeeper
          image: quay.io/sean.costello/zookeeper:3.4.14
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ZOO_MY_ID
              value: "$(MY_POD_NAME)"
            - name: ZOO_SERVERS
              value: "server.1=$(MY_POD_NAME).zookeeper-server.$(MY_POD_NAMESPACE).svc:2888:3888"
          ports:
            - name: client
              containerPort: 2181
              protocol: TCP
            - name: follower
              containerPort: 2888
              protocol: TCP
            - name: election
              containerPort: 3888
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /conf
              subPath: config
            - name: data
              mountPath: /data
              subPath: data
      volumes:
        - name: data
          emptyDir: {}