apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  type: ClusterIP
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: pfa
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  clusterIP: None
  ports:
    - name: client
      port: 2181
      protocol: TCP
      targetPort: client
    - name: follower
      port: 2888
      protocol: TCP
      targetPort: follower
    - name: election
      port: 3888
      protocol: TCP
      targetPort: election
  selector:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/instance: pfa